apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
  namespace: ecommerce
data:
  django-debug: "False"
  django-allowed-hosts: "ui-service,localhost,127.0.0.1"
  catalog-service-url: "http://catalog-service:8001"
  cart-service-url: "http://cart-service:8002"
  orders-service-url: "http://orders-service:8003"
  port: "8080"
  gunicorn-workers: "3"
  gunicorn-timeout: "30"
  log-level: "INFO"
