apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
  namespace: ecommerce
data:
  django-debug: "False"
  django-allowed-hosts: "orders-service,localhost,127.0.0.1"
  cart-service-url: "http://cart-service:8002"
  port: "8003"
  gunicorn-workers: "3"
  gunicorn-timeout: "30"
  log-level: "INFO"
