apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
data:
  django-debug: "False"
  django-allowed-hosts: "cart-service,localhost,127.0.0.1"
  redis-url: "redis://redis:6379/0"
  cart-ttl-seconds: "604800"
  cart-max-items: "50"
  cart-max-quantity-per-item: "99"
  catalog-service-url: "http://catalog-service:8001"
  catalog-service-timeout: "5"
  port: "8002"
  gunicorn-workers: "3"
  gunicorn-timeout: "30"
  log-level: "INFO"
  cors-allowed-origins: "http://ui-service:8080"
  cors-allow-all-origins: "False"