apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
  namespace: ecommerce
data:
  django-debug: "False"
  django-allowed-hosts: "catalog-service,localhost,127.0.0.1"
  port: "8001"
  gunicorn-workers: "3"
  gunicorn-timeout: "30"
  log-level: "INFO"
